### ISSUE TITLE
Package 'gazebo_ros' not found

### ISSUE THREAD

**Issue by MyGithubNotYours** [joshnewans/urdf_example#2]
Hi, thanks for the videos and directions! 

Unfortunately, I'm stuck. I'm trying to follow your directions from the video and webpage: https://articulatedrobotics.xyz/ready-for-ros-8-gazebo/

However this step:

- $ ros2 run gazebo_ros spawn_entity.py -topic robot_description -entity some_name

results in this error:

- Package 'gazebo_ros' not found

I already did:

- sudo apt install ros-foxy-gazebo-ros-pkgs

and tested that gazebo opens with 

- gazebo /usr/share/gazebo-11/worlds/seesaw.world

What am I missing?

**Comment by MyGithubNotYours** [comment]
Ah nevermind, I figured it out. I had sourced the /install/setup file in my workspace, but I didn't realize there was also a setup file in /opt/ros/foxy/ that needed to be sourced.

**Comment by joshnewans** [comment]
Glad you got it sorted!
