### ISSUE TITLE
Couldnt run on ros as a package

### ISSUE THREAD

**Issue by DvdZk** [joshnewans/urdf_example#3]
Srry, i have little experience with ros and thanks a lot for the video and the disposal of teaching. I tried to clone this repository as a package on my src folder and do a catkin_make but the compiler didnt recognize it as a catkin package and i dont know why :/ 

Thanks again for the video on teaching how to model a robot on xacro and i would appreciate any kind of help <3

**Comment by joshnewans** [comment]
Hi! It sounds like you are using ROS 1 since you are using catkin. This package is for ROS 2.

Since ROS 1 is no longer receiving major updates, if you are new to ROS (and especially if you are following my tutorials) you should use ROS 2.
